### ISSUE TITLE
print-values fails if values cannot be retrieved

### ISSUE THREAD

**Issue by CarstenGrohmann** [jedie/inverter-connect#49]
Hello, 

I get this exception when I query all values with an extended `deye_2mppt.yaml` definition. This definition is probably incorrect or some of the values are not queryable.

Affected version:
* current version from main branch

Full error log:
* [20230519_error_print-values.txt](https://github.com/jedie/inverter-connect/files/11519602/20230519_error_print-values.txt)

Please consider if you can fix this error.

Thank you,
Carsten

**Comment by jedie** [comment]
I update the the newest https://github.com/StephanJoubert/home_assistant_solarman/blob/main/custom_components/solarman/inverter_definitions/deye_2mppt.yaml that adds many values.

Looks currently like:

![grafik](https://github.com/jedie/inverter-connect/assets/71315/7b64cfcc-2e99-43f6-924d-8b3e9c0b3a20)
