### ISSUE TITLE
Mac error

### ISSUE THREAD

**Issue by m-reuter** [jedie/inverter-connect#57]
Hi, 

thanks for the awesome project!

when running the cli.py --help on a Mac it installed all dependencies as expected and then gives this error message:

> NotADirectoryError: Directory does not exists: "/etc/systemd/system"

Thanks for any help.

**Comment by mgraupner** [comment]
For a temporary fix comment the following line in inverter/user_settings.py (69) so it looks like this:

`#systemd: dataclasses = dataclasses.field(default_factory=SystemdServiceInfo)`

**Comment by jedie** [comment]
So sorry. I have to fix that. Systemd isn't available on mac ;)

**Comment by jedie** [comment]
It's fixed. Please test the new version.
