### ISSUE TITLE
Can't set time

### ISSUE THREAD

**Issue by basti122303** [jedie/inverter-connect#66]
Hello I use a SUN600 with Firmware MW3_16U_5406_1.57
I can't set a time:
`Check time by request "AT+NTPTM"...1970-1-1  0:0:1  Thur`
`Signing off with "AT+Q"...Goodbye ;)`

NTP didn't also work.
I have run tcpdump for some weeks. The last NTP query from the inverter is seen on 5 June 2023 but the time in the inverter is still 1970-1-1.
`30 │      AT+NTPTM │ 1970-1-1  0:17:27  Thur`
`31 │     AT+NTPSER │ cn.ntp.org.cn`
`32 │      AT+NTPRF │ 30`
`33 │      AT+NTPEN │ on`       
Did someone know what NTPRF is? Days? Hours? ...

**Comment by basti122303** [comment]
thanks a lot for the example.
Now it works so far.
I can only use IP's no hostnames, but this is an issue of deye I think.
`Use user settings file: /home/basti/.config/inverter-connect/inverter-connect.toml...read, ok.`
`inverter v0.11.1`
 `                                                                                                                                                (Set log level 0: ERROR)`
`InverterInfo(ip='10.0.0.31', mac='E8FDF89026CC', serial=4191779287)`
` `
`Fetch...NTPSER=pool.ntp.org,NTPEN=on,NTPTM,NTPSER,NTPRF,NTPEN,`
`Signing off with "AT+Q"...Goodbye ;)`
` `
`                     AT-command results                      `
`┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┓`
`┃ Counter ┃                Command ┃ Result                  ┃`
`┡━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━┩`
`│       1 │ AT+NTPSER=pool.ntp.org │ Not support domain name │`
`│       2 │            AT+NTPEN=on │                         │`
`│       3 │               AT+NTPTM │ 2023-6-28  19:2:16  Wed │`
`│       4 │              AT+NTPSER │ 192.168.30.1            │`
`│       5 │               AT+NTPRF │ 30                      │`
`│       6 │               AT+NTPEN │ `

**Comment by CarstenGrohmann** [comment]
@basti122303: You can enclose a block of code with 3 backticks. This makes it easier to read than each individual line in backticks. Please edit your comment to improve readability for other community members.

**Comment by basti122303** [comment]
done
